// examples/svelte/src/App.svelte
<script>
  // The view bound to Svelte state, a saved view to restore, a lock that
  // refuses the reader's changes, texts switched and changed in place, and a
  // grid that is taken out and put back, the way a route change does.
  import { OpengridGrid } from "@casoon/opengrid-svelte";

  // eslint-disable-next-line no-undef -- defined by vite.config.js
  const VERSION = __SVELTE_VERSION__;

  let { provider } = $props();

  const SAVED = { sort: [{ field: "customer", direction: "asc" }] };
  // One `$state` object, changed in place by "Say rows" — a change inside it
  // has to reach the grid as much as a new object does.
  const german_texts = $state({ lang: "de", matchesOne: "{count} Treffer", matchesOther: "{count} Treffer" });

  let view = $state({ sort: [{ field: "id", direction: "asc" }] });
  let selected = $state(0);
  let shown = $state(true);
  let german = $state(false);
  let locked = $state(false);
  let element = $state();

  // For the tests: what Svelte holds, and the element behind `bind:element`.
  $effect(() => {
    window.__view = $state.snapshot(view);
  });
  $effect(() => {
    window.__element = element;
  });
</script>

<main>
  <h1>opengrid in Svelte {VERSION}</h1>
  <p>
    <button type="button" onclick={() => (shown = !shown)}>
      {shown ? "Hide the grid" : "Show the grid"}
    </button>
    <button type="button" onclick={() => (view = SAVED)}>Restore the saved view</button>
    <button type="button" aria-pressed={german} onclick={() => (german = !german)}>German</button>
    <button type="button" onclick={() => (german_texts.matchesOther = "{count} Zeilen")}>Say rows</button>
    <button type="button" aria-pressed={locked} onclick={() => (locked = !locked)}>Lock the view</button>
  </p>
  <p id="selected">{selected} rows selected</p>
  {#if shown}
    <OpengridGrid
      label="Orders"
      datasource="orders"
      columns="id,customer,country,amount,qty"
      windowSize={40}
      selection
      toolbar
      class="orders"
      {provider}
      texts={german ? german_texts : undefined}
      bind:view={() => view, (next) => {
        if (!locked) view = next;
      }}
      bind:element
      onselectionchange={(detail) => (selected = detail.count)}
    />
  {/if}
</main>

// examples/angular/src/app/app.ts
// opengrid in Angular (plan point 81): the element in the template, supplied
// by the directive from docs/guides/frameworks.md, its view two-way bound (or
// one-way with `?one-way`), and a switch that takes the grid out and puts it
// back.
import { CUSTOM_ELEMENTS_SCHEMA, Component, VERSION, inject } from "@angular/core";
import type { SelectionChangeDetail, Texts, View } from "@casoon/opengrid";
import { OpengridDirective } from "./opengrid.directive";
import { ORDERS } from "./provider";

@Component({
  selector: "app-root",
  imports: [OpengridDirective],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <main>
      <h1>opengrid in Angular {{ version }}</h1>
      <p>
        <button type="button" (click)="shown = !shown">
          {{ shown ? "Hide the grid" : "Show the grid" }}
        </button>
        <button type="button" (click)="view = saved">Restore the saved view</button>
        <button type="button" [attr.aria-pressed]="german" (click)="german = !german">German</button>
      </p>
      <p id="selected">{{ selected }} rows selected</p>
      @if (shown) {
        @if (oneWay) {
          <!-- ?one-way: the page sets the view; the reader's change stays. -->
          <opengrid-grid
          opengrid
            label="Orders"
            datasource="orders"
            columns="id,customer,country,amount,qty"
            window-size="40"
            selection
            toolbar
            class="orders"
            [provider]="provider"
            [texts]="german ? germanTexts : undefined"
            [view]="view"
            (opengrid-selection-change)="onSelection($event)"
          ></opengrid-grid>
        } @else {
          <opengrid-grid
          opengrid
            label="Orders"
            datasource="orders"
            columns="id,customer,country,amount,qty"
            window-size="40"
            selection
            toolbar
            class="orders"
            [provider]="provider"
            [texts]="german ? germanTexts : undefined"
            [(view)]="view"
            (opengrid-selection-change)="onSelection($event)"
          ></opengrid-grid>
        }
      }
    </main>
  `,
})
export class App {
  protected readonly version = VERSION.full;
  protected readonly provider = inject(ORDERS);
  protected readonly saved: View = {
    sort: [{ field: "customer", direction: "asc" }],
  } as View;
  protected readonly germanTexts: Texts = {
    lang: "de",
    matchesOne: "{count} Treffer",
    matchesOther: "{count} Treffer",
  };
  /** `?one-way`: `[view]` instead of `[(view)]` (plan point 81). */
  protected readonly oneWay = location.search.includes("one-way");
  protected shown = true;
  protected german = false;
  protected selected = 0;

  private currentView: View | null = { sort: [{ field: "id", direction: "asc" }] } as View;

  /** The view as Angular holds it; mirrored onto `window` for the tests. */
  protected get view(): View | null {
    return this.currentView;
  }
  protected set view(next: View | null) {
    this.currentView = next;
    (window as unknown as { __view: View | null }).__view = next;
  }

  protected onSelection(event: Event): void {
    this.selected = (event as CustomEvent<SelectionChangeDetail>).detail.count;
  }
}
