// packages/opengrid-react/index.js
/**
 * React components for `@casoon/opengrid` (plan point 77, E32).
 *
 * A thin shell around `connect`: the component renders the custom element with
 * its attributes, and hands everything else — provider, texts, formats,
 * presentation, choices, the view and the three event callbacks — to one
 * connection. The rules of the module functions live in `connect`, not here.
 *
 * Three things only a React shell has to know:
 *
 * - **Attributes are rendered, not set later.** So they are in the server
 *   HTML too. A boolean attribute (`selection`, `toolbar`, …) is present or
 *   absent: React 18 would write `selection="false"` for `false`, and for a
 *   boolean attribute presence is what counts, so `true` becomes `""` and
 *   `false` leaves it out — the same in React 18 and 19.
 * - **StrictMode mounts twice in development**, and that costs nothing:
 *   `connect` applies only once the module has loaded, a microtask later at
 *   the earliest, so the first connection is disconnected before it has
 *   written anything, and only the second one asks the source.
 * - **An option is passed when it is set, or was set last time** — so a prop
 *   that goes away is reset (`connect`'s `undefined`), and one that was never
 *   there is not reset on every render.
 */

import { createElement, forwardRef, useEffect, useImperativeHandle, useRef } from "react";
import { connect } from "@casoon/opengrid";

/** What `connect` takes, by prop name. */
const OPTIONS = [
  "provider",
  "texts",
  "formats",
  "presentation",
  "choices",
  "view",
  "defaultView",
  "onViewChange",
  "onSelectionChange",
  "onCellChange",
];

/**
 * Builds one component.
 *
 * @param {string} tag the custom element.
 * @param {string} displayName the component's name in the React tools.
 * @param {Record<string, string>} attributes prop name → attribute name.
 * @param {string[]} booleans the props that are boolean attributes.
 */
function component(tag, displayName, attributes, booleans) {
  const Component = forwardRef(function OpengridComponent(props, ref) {
    const element = useRef(null);
    const connection = useRef(null);
    /** The options of the last render, to tell a removed prop from an absent one. */
    const previous = useRef({});
    useImperativeHandle(ref, () => element.current, []);

    const rendered = { ref: element };
    const options = {};
    for (const [name, value] of Object.entries(props)) {
      if (OPTIONS.includes(name)) {
        options[name] = value;
      } else if (name in attributes) {
        if (booleans.includes(name)) {
          rendered[attributes[name]] = value ? "" : undefined;
        } else {
          rendered[attributes[name]] = value == null ? undefined : String(value);
        }
      } else if (name === "className") {
        // `class` on a custom element: React 18 would write `classname`.
        rendered.class = value;
      } else {
        rendered[name] = value;
      }
    }

    // Unmount: the listeners go; the element keeps its state for as long as
    // it lives (docs/api.md §Connecting).
    useEffect(
      () => () => {
        connection.current?.disconnect();
        connection.current = null;
      },
      [],
    );

    // Every render: connect once, then update — `connect` writes only what
    // changed, so passing everything each time costs nothing.
    useEffect(() => {
      const last = previous.current;
      previous.current = options;
      if (connection.current) {
        const changed = {};
        for (const name of OPTIONS) {
          if (options[name] !== undefined || last[name] !== undefined) {
            changed[name] = options[name];
          }
        }
        connection.current.update(changed);
      } else {
        if (props.view != null && props.defaultView != null) {
          console.warn(
            `[opengrid] <${displayName}> has both view and defaultView; the view is controlled and leads`,
          );
        }
        connection.current = connect(element.current, options);
      }
    });

    return createElement(tag, rendered);
  });
  Component.displayName = displayName;
  return Component;
}

export const OpengridGrid = component(
  "opengrid-grid",
  "OpengridGrid",
  {
    label: "label",
    datasource: "datasource",
    columns: "columns",
    windowSize: "window-size",
    pageSize: "page-size",
    mode: "mode",
    groupBy: "group-by",
    search: "search",
    facets: "facets",
    toolbar: "toolbar",
    columnMenu: "column-menu",
    selection: "selection",
    density: "density",
  },
  ["search", "facets", "toolbar", "columnMenu", "selection"],
);

export const OpengridTable = component(
  "opengrid-table",
  "OpengridTable",
  { label: "label", datasource: "datasource", columns: "columns" },
  [],
);

export const OpengridPivot = component(
  "opengrid-pivot",
  "OpengridPivot",
  {
    label: "label",
    datasource: "datasource",
    rows: "rows",
    columns: "columns",
    values: "values",
  },
  [],
);

// packages/opengrid-svelte/Opengrid.svelte
<!--
  The element and its connection (plan point 79) — internal; the page uses
  OpengridGrid, OpengridTable and OpengridPivot.

  The element is rendered with its attributes, so they are in the server HTML
  too; everything else goes to one `connect` from `@casoon/opengrid`:

  - One effect reads every option — objects through `$state.snapshot`, so a
    change inside a `$state` object counts (for `formats`, the functions in it
    keep their identity) — and passes on what is set now or was set last time:
    a prop taken away is reset, one never given is left alone (the same rule
    as the React adapter).
  - `bind:view`: the view the reader changed is written into the bound prop;
    the effect then hands it back, and `connect` knows that is no change. A
    binding that refuses it (`bind:view={get, set}` whose setter keeps the old
    view) gets its own view written back after the tick — controlled, as in
    React and Vue. A `view={…}` without `bind:` follows Svelte's rule for
    bindable props: the reader's change becomes the component's own value,
    as a typed-in `value` does on an `<input>` without `bind:`.
  - `bind:element` gives the page the element, as `ref` does in React.
  - The connection is made once the element exists and closed when the
    component is destroyed. The element keeps its own state for as long as it
    lives (docs/api.md §Connecting).
-->
<script>
  import { tick, untrack } from "svelte";
  import { connect } from "@casoon/opengrid";

  let {
    tag,
    attributes,
    view = $bindable(),
    element = $bindable(),
    defaultView,
    provider,
    texts,
    formats,
    presentation,
    choices,
    onviewchange,
    onselectionchange,
    oncellchange,
    ...rest
  } = $props();

  let connection = null;
  let previous = {};

  $effect(() => {
    const options = {
      provider,
      texts: $state.snapshot(texts),
      formats: formats && snapshotFormats(formats),
      presentation: $state.snapshot(presentation),
      choices: $state.snapshot(choices),
      view: $state.snapshot(view),
      defaultView: $state.snapshot(defaultView),
    };
    untrack(() => {
      const callbacks = {
        onViewChange: (next) => {
          view = next;
          onviewchange?.(next);
          tick().then(() => {
            if (view != null) connection?.update({ view: $state.snapshot(view) });
          });
        },
        onSelectionChange: (detail) => onselectionchange?.(detail),
        onCellChange: (detail) => oncellchange?.(detail),
      };
      if (!connection) {
        if (options.view != null && options.defaultView != null) {
          console.warn(`[opengrid] <${tag}> has both view and defaultView; the view is controlled and leads`);
        }
        const set = Object.entries(options).filter(([, value]) => value !== undefined);
        connection = connect(element, { ...Object.fromEntries(set), ...callbacks });
      } else {
        const changed = { ...callbacks };
        for (const [name, value] of Object.entries(options)) {
          if (value !== undefined || previous[name] !== undefined) {
            changed[name] = value;
          }
        }
        connection.update(changed);
      }
      previous = options;
    });
  });

  /** The formats as plain values, their functions kept as they are. */
  function snapshotFormats(value) {
    return Object.fromEntries(
      Object.entries(value).map(([column, format]) => [
        column,
        typeof format === "function" ? format : $state.snapshot(format),
      ]),
    );
  }

  $effect(() => () => {
    connection?.disconnect();
    connection = null;
  });
</script>

<svelte:element this={tag} bind:this={element} {...attributes} {...rest}></svelte:element>
